#!/bin/bash

if [ -z "$1" ]; then
	if [ -f ".env" ]; then
		#do nothing
		:
	else
		echo "copying .env.example to .env; you can change this later"
		#@Todo add mongo database initial setup here
		cp .env.example .env
	fi
	docker-compose --project-name mithril stop
	docker-compose --project-name mithril run --rm mithril yarn
	docker-compose --project-name mithril up -d
	echo "Started containers in detach mode."
	echo "Connecting to cli. please press enter to continue ... "
	docker attach mithril_mithril_1
	:
elif [ "$1" == "cli" ]; then
	docker exec -it mithril_mithril_1 bash
else
	docker-compose --project-name mithril $1
fi
