#!/bin/bash

if [ -z "$1" ]; then
	if [ -f ".env" ]; then
		#do nothing
		:
	else
		echo "copying .env.example to .env; you can change this later"
		#@Todo add mongo database initial setup here
		cp .env.example .env
	fi
	docker-compose --project-name valinor stop
	docker-compose --project-name valinor run --rm valinor yarn
	docker-compose --project-name valinor up -d
	echo "Started containers in detach mode."
	echo "Connecting to cli. please press enter to continue ... "
	docker attach valinor_valinor_1
	:
elif [ "$1" == "cli" ]; then
	docker exec -it valinor_valinor_1 bash
else
	docker-compose --project-name valinor $1
fi
